services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build

