services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production

    - type: web
    name: frontend
        runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build

